services:
  # 🧠 AUTH service
  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    volumes:
      - ./auth-service:/var/www
    expose:
      - "9000"
    networks:
      app-network:
        aliases:
          - php

  nginx-auth:
    image: nginx:stable
    container_name: nginx-auth
    volumes:
    - ./auth-service:/var/www
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./nginx/certs:/etc/nginx/ssl
    ports:
      - "8443:443"
    depends_on:
      - auth-service
    networks:
      - app-network

  auth-db:
    image: mysql:8
    container_name: auth-db
    environment:
      MYSQL_DATABASE: auth_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - auth-db-data:/var/lib/mysql
    networks:
      - app-network

  # 📚 BOOKING service
  booking-service:
    build:
      context: ./booking-service
    container_name: booking-service
    volumes:
      - ./booking-service:/var/www
    expose:
      - "9000"
    networks:
      app-network:
        aliases:
          - php

  nginx-booking:
    image: nginx:stable
    container_name: nginx-booking
    volumes:
      - ./booking-service:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/ssl
    ports:
      - "8444:443"
    networks:
      - app-network

  booking-db:
    image: mysql:8
    container_name: booking-db
    environment:
      MYSQL_DATABASE: booking_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - booking-db-data:/var/lib/mysql
    networks:
      - app-network

  # 💳 PAYMENT service
  payment-service:
    build:
      context: ./payment-service
    container_name: payment-service
    volumes:
      - ./payment-service:/var/www
    expose:
      - "9000"
    networks:
      app-network:
        aliases:
          - php

  nginx-payment:
    image: nginx:stable
    container_name: nginx-payment
    volumes:
      - ./payment-service:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/ssl
    ports:
      - "8445:443"
    depends_on:
      - payment-service
    networks:
      - app-network

  payment-db:
    image: mysql:8
    container_name: payment-db
    environment:
      MYSQL_DATABASE: payment_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - payment-db-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  auth-db-data:
  booking-db-data:
  payment-db-data:

networks:
  app-network:
    driver: bridge
